# Rendered by install-gitlab.sh using envsubst. Variables:
#   ${GITLAB_DOMAIN}
#   ${GITLAB_NAMESPACE}
global:
  edition: ce
  hosts:
    domain: ${GITLAB_DOMAIN}
    gitlab:
      name: gitlab.${GITLAB_DOMAIN}
    registry:
      name: registry.${GITLAB_DOMAIN}
    minio:
      name: minio.${GITLAB_DOMAIN}
    smartcard:
      name: smartcard.${GITLAB_DOMAIN}
    kas:
      name: kas.${GITLAB_DOMAIN}
  ingress:
    class: nginx
    configureCertmanager: false
    enabled: true
    tls:
      enabled: false
  minio:
    enabled: true
  gitaly:
    persistence:
      enabled: true
      size: 40Gi
  psql:
    enabled: false
  redis:
    password:
      enabled: false
  appConfig:
    enableUsagePing: false
    omniauth:
      enabled: false

certmanager:
  install: false
  installCRDs: false

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

kas:
  enabled: false

registry:
  hpa:
    enabled: false

upgradeCheck:
  enabled: false

gitlab:
  gitaly:
    persistence:
      enabled: true
      size: 40Gi
  webservice:
    minReplicas: 1
    maxReplicas: 1
    ingress:
      path: /
    hpa:
      minReplicas: 1
      maxReplicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 4Gi
      requests:
        cpu: 250m
        memory: 2Gi
  sidekiq:
    replicas:
      default: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1

postgresql:
  install: true
  global:
    postgresql:
      auth:
        # Adjust these credentials before deploying to production environments.
        postgresPassword: changeme
        username: gitlab
        password: changeme
        database: gitlabhq_production
  primary:
    persistence:
      enabled: true
      size: 40Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi

redis:
  install: true
  master:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

minio:
  persistence:
    size: 40Gi

shared-secrets:
  self-signed-cert:
    generate: true
