apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rundeck
  namespace: workflow
  labels:
    app: rundeck
spec:
  storageClassName: local-path 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
