cluster:
  name: kubernetes
k8sServiceHost: apiserver.cluster.local
k8sServicePort: 6443
kubeProxyReplacement: true
ipam:
  mode: "kubernetes"
nodePort:
  enabled: true
externalIPs:
  enabled: true
hostServices:
  enabled: true
enableIPv4Masquerade: true
envoy:
  enabled: false
operator:
  replicas: 1
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
