name: Build & push apline with custom ca image
on:
  pull_request:
  push:
    paths:
      - 'oci/base/alpine/Dockerfile'
      - '.github/workflows/alpine-with-custom-ca.yaml'
    branches:
      - main

jobs:
  base-image:
    runs-on: ubuntu-latest
    name: Build alpine base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push alpine with custom ca image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: './oci/base/alpine'
          build_file: 'Dockerfile' 
          image: k8s/alpine-ca
          tag: latest
          cache: true
          cache_registry: cache
