name: Build & push apline-glibc image
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/alpine-glibc-image.yaml'
      - 'oci/base/alpine-glibc/Dockerfile'
    branches:
      - main

jobs:
  base-image:
    runs-on: self-hosted
    name: Build alpine-glibc base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push alpine-glibc image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: '.oci/base/alpine-glibc'
          build_file: 'Dockerfile'
          image: k8s/alpine-glibc
          tag: 2.34
          cache: true
          cache_registry: cache
