name: Build & push apline-awscli image
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/alpine-awscli.yaml'
      - 'oci/base/alpine-awscli/Dockerfile'
    branches:
      - main

jobs:
  base-image:
    runs-on: ubuntu-latest
    name: Build alpine-awscli base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push alpine-awscli image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: 'oci/base/alpine-awscli'
          build_file: 'Dockerfile'
          image: k8s/alpine-awscli
          tag: 2.6.1
          cache: true
          cache_registry: cache
