name: build & push ci base images

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-ci-images.yml'
      - 'oci/base/alpine-image-builder/Dockerfile' 
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-ci-images.yml'
      - 'oci/base/alpine-image-builder/Dockerfile' 
  workflow_dispatch:
    branches:
      - main
env:
  IMAGE_REPO: "artifact.onwalk.net"

jobs:
  build-ansible-lint-image:
    name: Build ansible lint image
    uses: svc-design/actions/.github/workflows/build-images-with-host-docker.yaml@main
    with:
      registry_addr: "artifact.onwalk.net"
      image_name: 'public/base/alpine-ansible-lint'
      image_tag: 'latest'
      dockerfile_path: 'oci/base/alpine-ansible-lint'
    secrets:
      artifactory_sa: ${{ secrets.REPO_USER }}
      artifactory_pw: ${{ secrets.HELM_REPO_PASSWORD }}
