name: build images alpine-docker-dind

on:
  pull_request:
    branches:
      - main
    paths:
      - 'oci/base/alpine-docker-dind/Dockerfile'
      - '.github/workflows/build-ci-image-docker-dind.yml'
  workflow_dispatch:
    branches:
      - main
env:
  IMAGE_REPO: "artifact.onwalk.net"

jobs:
  eslint:
    name: Build Docker in Docker image
    uses: svc-design/actions/.github/workflows/build-images.yaml@main
    with:
      method: 'docker/node'
      registry_addr: "harbor.onwalk.net"
      dockerfile_path: 'oci/base/alpine-docker-dind'
      image_name: 'public/base/alpine-docker-dind'
      image_tag: 'latest'
    secrets:
      artifactory_sa: ${{ secrets.REPO_USER }}
      artifactory_pw: ${{ secrets.HELM_REPO_PASSWORD }}
