name: build images ansible-runner

on:
  pull_request:
    branches:
      - main
    paths:
      - 'oci/base/alpine-ansible-lint/Dockerfile'
      - '.github/workflows/build-ci-image-ansible-runer.yml'
  workflow_dispatch:
    branches:
      - main
env:
  IMAGE_REPO: "artifact.onwalk.net"

jobs:
  eslint:
    name: Build Docker in Docker image
    uses: svc-design/actions/.github/workflows/build-images.yaml@main
    with:
      method: 'docker/node'
      registry_addr: "harbor.onwalk.net"
      dockerfile_path: 'oci/base/alpine-ansible-lint'
      image_name: 'public/base/alpine-ansible-runer'
      image_tag: 'latest'
    secrets:
      artifactory_sa: ${{ secrets.REPO_USER }}
      artifactory_pw: ${{ secrets.HELM_REPO_PASSWORD }}
