name: build images node-runtime

on:
  pull_request:
    branches:
      - main
    paths:
      - 'base-images/node-runtime.Dockerfile'
      - '.github/workflows/build-node-runtime-base-images.yml'
  workflow_dispatch:

jobs:
  build-node-runtime:
    name: build node runtime image
    uses: svc-design/actions/.github/workflows/build-images.yaml@main
    with:
      method: 'docker/node'
      registry_addr: images.onwalk.net
      dockerfile_path: 'base-images/node-runtime.Dockerfile'
      image_name: 'public/base/node-runtime'
      image_tag: 'latest'
    secrets:
      artifactory_sa: ${{ secrets.IMAGES_REPO_USER }}
      artifactory_pw: ${{ secrets.IMAGES_REPO_PASSWORD }}
