name: build images openresty-geoip

on:
  pull_request:
    branches:
      - main
    paths:
      - 'base-images/openresty-geoip.Dockerfile'
      - '.github/workflows/build-openresty-geoip-base-images.yml'
  workflow_dispatch:

jobs:
  build-openresty-geoip:
    name: build openresty geoip image
    uses: svc-design/actions/.github/workflows/build-images.yaml@main
    with:
      method: 'docker/node'
      registry_addr: images.onwalk.net
      dockerfile_path: 'base-images/openresty-geoip.Dockerfile'
      image_name: 'public/base/openresty-geoip'
      image_tag: 'latest'
    secrets:
      artifactory_sa: ${{ secrets.IMAGES_REPO_USER }}
      artifactory_pw: ${{ secrets.IMAGES_REPO_PASSWORD }}
