name: build images python-3.10

on:
  pull_request:
    branches:
      - main
    paths:
      - 'oci/base/python-3.10/Dockerfile'
      - '.github/workflows/build-python-3.10-base-images.yml'
  workflow_dispatch:
    branches:
      - main

jobs:
  build-python-3-10:
    name: build python 3.10 images
    uses: svc-design/actions/.github/workflows/build-images.yaml@main
    with:
      method: 'docker/node'
      registry_addr: images.onwalk.net
      dockerfile_path: 'oci/base/python-3.10'
      image_name: 'public/base/python-3.10'
      image_tag: 'latest'
    secrets:
      artifactory_sa: ${{ secrets.IMAGES_REPO_USER }}
      artifactory_pw: ${{ secrets.IMAGES_REPO_PASSWORD }}
