name: Build & push chart builder apline base image
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/datadog-agent.yaml'
      - 'oci/datadog-cluster-agent/Dockerfile'
    branches:
      - main

jobs:
  datadog-agent:
    runs-on: ubuntu-latest
    name: build chart builder datadog-cluster-agent image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push datadog-cluster-agent image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: 'oci/datadog-cluster-agent/'
          build_file: 'Dockerfile'
          image: public/datadog-cluster-agent
          tag: latest
          cache: false
          cache_registry: cache
