name: Build & push flux-helm-controller image
on:
  pull_request:
  push:
    paths:
      - 'base/alpine/Dockerfile'
      - 'fluxcd/flux-helm-controller.Dockerfile'
      - '.github/workflows/alpine-with-custom-ca.yaml'
      - '.github/workflows/flux-helm-controller-image.yaml'
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: base-image
    name: Build docker image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push fluxcd/helm-controller image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          build_file: fluxcd/flux-helm-controller.Dockerfile
          image: k8s/fluxcd/helm-controller
          tag: v0.22.1
          cache: true
          cache_registry: cache
  base-image:
    runs-on: ubuntu-latest
    name: Build alpine base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push alpine with custom ca image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          build_file: base/alpine/Dockerfile 
          image: k8s/alpine-ca
          tag: latest
          cache: true
          cache_registry: cache
