name: Build & push flux-kustomize-controller image
on:
  pull_request:
  push:
    paths:
      - 'fluxcd/flux-kustomize-controller.Dockerfile'
      - '.github/workflows/fluxcd/flux-kustomize-controller-image.yaml'
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push fluxcd/kustomize-controller image'
        uses: aevea/action-kaniko@v0.10.0
        with:
          registry: artifact.onwalk.net
          username: admin
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          build_file: fluxcd/flux-kustomize-controller.Dockerfile
          image: public/fluxcd/kustomize-controller
          tag: v0.26.2
          cache: true
          cache_registry: cache
