name: Build & push k8s app runner apline base image
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/kube-tools-alpine.yaml'
      - 'oci/app-runner/kube-tools-alpine/ca.crt'
      - 'oci/app-runner/kube-tools-alpine/Makefile'
      - 'oci/app-runner/kube-tools-alpine/Dockerfile'
      - 'oci/app-runner/kube-tools-alpine/repositories'
    branches:
      - main

jobs:
  base-image:
    runs-on: ubuntu-latest
    name: build k8s app runner alpine base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push k8s app runner alpine base image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: 'oci/app-runner/kube-tools-alpine/'
          build_file: 'Dockerfile'
          image: devops/kube-tools-alpine
          tag: latest
          cache: false
          cache_registry: cache
