name: Build Offline n8n Installer

on:
  push:
    paths:
      - 'gitops/scripts/n8n/**'
      - '.github/workflows/offline-package-n8n.yaml'
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to use/sync (e.g., v0.1.0). Leave empty to use offline-n8n-<run_number>"
        required: false
        type: string
      n8n_tag:
        description: "n8n container tag (default: latest)"
        required: false
        type: string
      postgres_tag:
        description: "Postgres image tag (default: 15-alpine)"
        required: false
        type: string

permissions:
  contents: write

concurrency:
  group: build-offline-n8n
  cancel-in-progress: false

jobs:
  build-offline-installer:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    outputs:
      n8n_tag: ${{ steps.resolve.outputs.n8n_tag }}
      postgres_tag: ${{ steps.resolve.outputs.postgres_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Resolve image tags
        id: resolve
        env:
          INPUT_N8N_TAG: ${{ github.event.inputs.n8n_tag }}
          INPUT_POSTGRES_TAG: ${{ github.event.inputs.postgres_tag }}
        run: |
          set -euo pipefail
          N8N_TAG=${INPUT_N8N_TAG:-latest}
          POSTGRES_TAG=${INPUT_POSTGRES_TAG:-15-alpine}
          {
            echo "n8n_tag=${N8N_TAG}"
            echo "postgres_tag=${POSTGRES_TAG}"
          } >> "$GITHUB_OUTPUT"

      - name: Prepare directories
        run: |
          set -euo pipefail
          rm -rf offline-installer
          mkdir -p offline-installer/{images,scripts}

      - name: Stage compose file and scripts
        env:
          N8N_TAG: ${{ steps.resolve.outputs.n8n_tag }}
          POSTGRES_TAG: ${{ steps.resolve.outputs.postgres_tag }}
        run: |
          set -euo pipefail
          cp gitops/scripts/n8n/docker-compose.yaml offline-installer/docker-compose.yaml
          sed -i "s/__N8N_TAG__/${N8N_TAG}/g" offline-installer/docker-compose.yaml
          sed -i "s/__POSTGRES_TAG__/${POSTGRES_TAG}/g" offline-installer/docker-compose.yaml
          cp gitops/scripts/n8n/deploy-n8n.sh offline-installer/scripts/
          chmod +x offline-installer/scripts/deploy-n8n.sh
          cat <<'README' > offline-installer/README.md
# Offline n8n Installer

This archive contains container images and helper assets for deploying n8n with Docker Compose.

## Contents
- `docker-compose.yaml`: Reference deployment manifest configured for the packaged images.
- `images/`: Pre-pulled container images saved as tar archives.
- `scripts/deploy-n8n.sh`: Helper script to load the images and manage the compose stack.

## Usage
1. Extract the archive on a host with Docker/nerdctl available.
2. (Optional) Run `IMAGE_LOAD_TOOL=nerdctl ./scripts/deploy-n8n.sh load-images` to import the images with nerdctl.
3. Start the stack: `./scripts/deploy-n8n.sh up`.
4. Access the n8n UI at http://localhost:5678.

Adjust the compose file as needed before running the helper script.
README

      - name: Pull & export container images
        env:
          N8N_TAG: ${{ steps.resolve.outputs.n8n_tag }}
          POSTGRES_TAG: ${{ steps.resolve.outputs.postgres_tag }}
        run: |
          set -euo pipefail
          images=(
            "n8nio/n8n:${N8N_TAG}"
            "postgres:${POSTGRES_TAG}"
          )
          for image in "${images[@]}"; do
            docker pull "$image"
            safe=$(echo "$image" | tr '/:' '-_')
            docker save "$image" -o "offline-installer/images/${safe}.tar"
          done

      - name: Package offline installer
        run: |
          set -euo pipefail
          tar -czf offline-package-n8n-${{ matrix.arch }}.tar.gz -C offline-installer .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: offline-package-n8n-${{ matrix.arch }}
          path: offline-package-n8n-${{ matrix.arch }}.tar.gz

  test-offline-installer:
    needs: build-offline-installer
    strategy:
      matrix:
        arch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: offline-package-n8n-${{ matrix.arch }}
          path: offline-test

      - name: Verify archive integrity
        run: |
          set -euo pipefail
          cd offline-test
          tar -tzf offline-package-n8n-${{ matrix.arch }}.tar.gz > /dev/null

  publish-release:
    needs: test-offline-installer
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || format('offline-n8n-{0}', github.run_number) }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Build ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: offline-package-n8n-amd64
          path: release-artifacts/amd64

      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: offline-package-n8n-arm64
          path: release-artifacts/arm64

      - name: Upload offline installers to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            release-artifacts/amd64/offline-package-n8n-amd64.tar.gz
            release-artifacts/arm64/offline-package-n8n-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
