name: Sync Images for Vector

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - '.github/workflows/sync-images-vector.yaml'
  push:
    paths:
      - '.github/workflows/sync-images-vector.yaml'
  workflow_dispatch:
    branches:
      - main

jobs:
  harbor-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize and Sync Vector images
        env:
          USER: ${{ secrets.IMAGES_REPO_USER }}
          PASSWORD: ${{ secrets.IMAGES_REPO_PASSWORD }}
        shell: bash
        run: |
          sudo apt update && sudo apt install -y git
          echo "$PASSWORD" | docker login --username=$USER --password-stdin images.onwalk.net
          docker pull docker.io/timberio/vector:0.37.1-distroless-libc
          docker tag docker.io/timberio/vector:0.37.1-distroless-libc images.onwalk.net/public/timberio/vector:0.37.1-distroless-libc
          docker push images.onwalk.net/public/timberio/vector:0.37.1-distroless-libc

