name: sync images for Mysql

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - '.github/workflows/sync-images-mysql.yaml'
  workflow_dispatch:
    branches:
      - main

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initialization environment
      env:
        USER: ${{ secrets.IMAGES_REPO_USER }}
        PASSWORD: ${{ secrets.IMAGES_REPO_PASSWORD }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install git -y
        echo "$PASSWORD" | docker login --username=$USER --password-stdin images.onwalk.net

    - name: sync images
      shell: bash
      run: |
        function sync_image()
        {
          local src_image=$1
          local dest_image=$2
          docker pull $src_image
          docker tag  $src_image $dest_image
          docker push $dest_image
        }
        sync_image "docker.io/library/redis:alpine" "images.onwalk.net/public/redis:alpine"
        sync_image "docker.io/otel/opentelemetry-collector-contrib:0.62.0" "images.onwalk.net/public/opentelemetry-collector-contrib:0.62.0"
        #sync_image "busybox:1.32" "images.onwalk.net/public/busybox:1.32"
        #sync_image "docker.io/mysql:5.7.30" "images.onwalk.net/public/database/mysql:5.7.30"
