name: Sync Images

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/sync-images.yaml'
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}

    - name: Initialization environment
      env:
        REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install git -y
        sudo timedatectl set-timezone "$TZ"
        echo "$REPO_PASSWORD" | docker login --username=admin --password-stdin artifact.onwalk.net

    - name: Sync images
      shell: bash
      run: |
        docker pull gcr.io/kaniko-project/executor:debug
        docker tag gcr.io/kaniko-project/executor:debug artifact.onwalk.net/k8s/kaniko-executor:debug
        docker push artifact.onwalk.net/k8s/kaniko-executor:debug

        docker pull gcr.io/kaniko-project/executor:v1.9.1
        docker tag gcr.io/kaniko-project/executor:v1.9.1 artifact.onwalk.net/k8s/kaniko-executor:1.9.1
        docker push artifact.onwalk.net/k8s/kaniko-executor:1.9.1

        docker pull gcr.io/kaniko-project/executor:v1.9.1-debug
        docker tag gcr.io/kaniko-project/executor:v1.9.1-debug artifact.onwalk.net/k8s/kaniko-executor:1.9.1-debug
        docker push artifact.onwalk.net/k8s/kaniko-executor:1.9.1-debug

        docker pull hashicorp/terraform:latest
        docker tag hashicorp/terraform:latest artifact.onwalk.net/k8s/terraform:latest
        docker push artifact.onwalk.net/k8s/terraform:latest

        docker pull datadog/cluster-agent:latest
        docker tag datadog/cluster-agent:latest artifact.onwalk.net/k8s/datadog/cluster-agent:latest
        docker push artifact.onwalk.net/k8s/datadog/cluster-agent:latest

        docker pull datadog/cluster-agent:7.43.1
        docker tag datadog/cluster-agent:7.43.1 artifact.onwalk.net/k8s/datadog/cluster-agent:7.43.1
        docker push artifact.onwalk.net/k8s/datadog/cluster-agent:7.43.1

        docker pull datadog/agent:7.43.1
        docker tag datadog/agent:7.43.1 artifact.onwalk.net/k8s/datadog/agent:7.43.1
        docker push artifact.onwalk.net/k8s/datadog/agent:7.43.1

        docker pull checkoutservice:latest
        docker tag checkoutservice:latest  artifact.onwalk.net/pubilc/checkoutservice:latest
        docker pull artifact.onwalk.net/pubilc/checkoutservice:latest

        docker pull frontend:latest
        docker tag  frontend:latest  artifact.onwalk.net/pubilc/frontend:latest
        docker pull artifact.onwalk.net/pubilc/frontend:latest

        docker pull paymentservice:latest
        docker tag paymentservice:latest  artifact.onwalk.net/pubilc/paymentservice:latest
        docker pull artifact.onwalk.net/pubilc/paymentservice:latest

        docker pull redis:alpine
        docker tag redis:alpine  artifact.onwalk.net/pubilc/redis:alpine
        docker pull artifact.onwalk.net/pubilc/redis:alpine

        docker pull adservice
        docker tag adservice:latest  artifact.onwalk.net/pubilc/adservice:latest
        docker pull artifact.onwalk.net/pubilc/adservice:latest

        docker pull currencyservice
        docker tag currencyservice:latest  artifact.onwalk.net/pubilc/currencyservice:latest
        docker pull artifact.onwalk.net/pubilc/currencyservice:latest

        docker pull productcatalogservice
        docker tag productcatalogservice:latest  artifact.onwalk.net/pubilc/productcatalogservice:latest
        docker pull artifact.onwalk.net/pubilc/productcatalogservice:latest

        docker pull shippingservice
        docker tag shippingservice:latest  artifact.onwalk.net/pubilc/shippingservice:latest
        docker pull artifact.onwalk.net/pubilc/shippingservice:latest

        docker pull cartservice
        docker tag cartservice:latest  artifact.onwalk.net/pubilc/cartservice:latest
        docker pull artifact.onwalk.net/pubilc/cartservice:latest

        docker pull emailservice
        docker tag emailservice:latest  artifact.onwalk.net/pubilc/emailservice:latest
        docker pull artifact.onwalk.net/pubilc/emailservice:latest

        docker pull busybox
        docker tag busybox:latest  artifact.onwalk.net/pubilc/busybox:latest
        docker pull artifact.onwalk.net/pubilc/busybox:latest

        docker pull loadgenerator
        docker tag loadgenerator:latest  artifact.onwalk.net/pubilc/loadgenerator:latest
        docker pull artifact.onwalk.net/pubilc/loadgenerator:latest
