backup:
  type: full  # 选项：full（全量），incremental（增量）
  schedule: "0 2 * * *"  # 自动备份的 Cron 表达式，默认为每天凌晨 2 点
  encryption: true
  storage:
    provider: aliyun  # 选项：aws，gcp，azure，aliyun（阿里云 OSS）
    bucket_name: your-bucket-name
    access_key: YOUR_ACCESS_KEY
    secret_key: YOUR_SECRET_KEY
    endpoint: oss-cn-hangzhou.aliyuncs.com  # 阿里云 OSS 的 Endpoint
restore:
  source: latest  # 或者指定特定的备份文件
  storage:
    provider: aliyun
    bucket_name: your-bucket-name
    access_key: YOUR_ACCESS_KEY
    secret_key: YOUR_SECRET_KEY
    endpoint: oss-cn-hangzhou.aliyuncs.com
verification:
  enabled: true
  schedule: "0 3 * * *"  # 备份验证的 Cron 表达式
